---
.travis.yml:
  acceptance:
    - '*'
  use_containers: false
  install: 
    - "travis_retry ./.travis.sh"
  script:
    - bundle exec rake validate
    - bundle exec rake lint
    - AUGEAS_LENS_LIB=files/lenses bundle exec rake spec SPEC_OPTS='--format documentation'
    - bundle exec rake metadata
  secure: "etCGQI0hjcKLcm7WcdUONSCh3TWM+SSoqCVMdMsulcVKeAR2CWPSi2nga7TKsDAlKQ2XxXPVYcBpFf+p0gxbAvV4jCFNU96KTtHAMkJbIASYhtHr9Ixk/ToG6hhdywvjAZRS7xvAOwUgWEoA6gA0jJy5nNu+hUZRpvdPreM/DgE="
  extras:
    - rvm: default
      sudo: required
      services: docker
      env: BEAKER_set="debian-7-x86_64-docker" PUPPET_AIO="yes"
      bundler_args:
      script: bundle exec rspec spec/acceptance/*_spec.rb
    - rvm: default
      sudo: required
      services: docker
      env: BEAKER_set="centos-6-x86_64-docker" PUPPET_AIO="yes"
      bundler_args:
      script: bundle exec rspec spec/acceptance/*_spec.rb
    - rvm: default
      sudo: required
      services: docker
      env: BEAKER_set="centos-7-x86_64-docker" PUPPET_AIO="yes"
      bundler_args:
      script: bundle exec rspec spec/acceptance/*_spec.rb
spec/spec_helper.rb:
  augeasproviders: true
